<?php
/**
 * IngestOut
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Model;

use \ArrayAccess;
use \Hanzo\Cloud\ObjectSerializer;

/**
 * IngestOut Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IngestOut implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ingestOut';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attempts_ingested' => 'int',
        'attempts_retained' => 'int',
        'canonical_attempts' => 'int',
        'canonical_experiments' => 'int',
        'experiments_ingested' => 'int',
        'experiments_retained' => 'int',
        'project' => 'string',
        'rolled_up' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attempts_ingested' => null,
        'attempts_retained' => null,
        'canonical_attempts' => null,
        'canonical_experiments' => null,
        'experiments_ingested' => null,
        'experiments_retained' => null,
        'project' => null,
        'rolled_up' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attempts_ingested' => false,
        'attempts_retained' => false,
        'canonical_attempts' => false,
        'canonical_experiments' => false,
        'experiments_ingested' => false,
        'experiments_retained' => false,
        'project' => false,
        'rolled_up' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attempts_ingested' => 'attempts_ingested',
        'attempts_retained' => 'attempts_retained',
        'canonical_attempts' => 'canonical_attempts',
        'canonical_experiments' => 'canonical_experiments',
        'experiments_ingested' => 'experiments_ingested',
        'experiments_retained' => 'experiments_retained',
        'project' => 'project',
        'rolled_up' => 'rolled_up'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attempts_ingested' => 'setAttemptsIngested',
        'attempts_retained' => 'setAttemptsRetained',
        'canonical_attempts' => 'setCanonicalAttempts',
        'canonical_experiments' => 'setCanonicalExperiments',
        'experiments_ingested' => 'setExperimentsIngested',
        'experiments_retained' => 'setExperimentsRetained',
        'project' => 'setProject',
        'rolled_up' => 'setRolledUp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attempts_ingested' => 'getAttemptsIngested',
        'attempts_retained' => 'getAttemptsRetained',
        'canonical_attempts' => 'getCanonicalAttempts',
        'canonical_experiments' => 'getCanonicalExperiments',
        'experiments_ingested' => 'getExperimentsIngested',
        'experiments_retained' => 'getExperimentsRetained',
        'project' => 'getProject',
        'rolled_up' => 'getRolledUp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attempts_ingested', $data ?? [], null);
        $this->setIfExists('attempts_retained', $data ?? [], null);
        $this->setIfExists('canonical_attempts', $data ?? [], null);
        $this->setIfExists('canonical_experiments', $data ?? [], null);
        $this->setIfExists('experiments_ingested', $data ?? [], null);
        $this->setIfExists('experiments_retained', $data ?? [], null);
        $this->setIfExists('project', $data ?? [], null);
        $this->setIfExists('rolled_up', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attempts_ingested
     *
     * @return int|null
     */
    public function getAttemptsIngested()
    {
        return $this->container['attempts_ingested'];
    }

    /**
     * Sets attempts_ingested
     *
     * @param int|null $attempts_ingested AttemptsIngested is how many attempt versions this call appended.
     *
     * @return self
     */
    public function setAttemptsIngested($attempts_ingested)
    {
        if (is_null($attempts_ingested)) {
            throw new \InvalidArgumentException('non-nullable attempts_ingested cannot be null');
        }
        $this->container['attempts_ingested'] = $attempts_ingested;

        return $this;
    }

    /**
     * Gets attempts_retained
     *
     * @return int|null
     */
    public function getAttemptsRetained()
    {
        return $this->container['attempts_retained'];
    }

    /**
     * Sets attempts_retained
     *
     * @param int|null $attempts_retained AttemptsRetained is the full versioned attempt history the store now holds.
     *
     * @return self
     */
    public function setAttemptsRetained($attempts_retained)
    {
        if (is_null($attempts_retained)) {
            throw new \InvalidArgumentException('non-nullable attempts_retained cannot be null');
        }
        $this->container['attempts_retained'] = $attempts_retained;

        return $this;
    }

    /**
     * Gets canonical_attempts
     *
     * @return int|null
     */
    public function getCanonicalAttempts()
    {
        return $this->container['canonical_attempts'];
    }

    /**
     * Sets canonical_attempts
     *
     * @param int|null $canonical_attempts CanonicalAttempts is the deduped attempt count the store now holds.
     *
     * @return self
     */
    public function setCanonicalAttempts($canonical_attempts)
    {
        if (is_null($canonical_attempts)) {
            throw new \InvalidArgumentException('non-nullable canonical_attempts cannot be null');
        }
        $this->container['canonical_attempts'] = $canonical_attempts;

        return $this;
    }

    /**
     * Gets canonical_experiments
     *
     * @return int|null
     */
    public function getCanonicalExperiments()
    {
        return $this->container['canonical_experiments'];
    }

    /**
     * Sets canonical_experiments
     *
     * @param int|null $canonical_experiments CanonicalExperiments is the deduped experiment count the store now holds.
     *
     * @return self
     */
    public function setCanonicalExperiments($canonical_experiments)
    {
        if (is_null($canonical_experiments)) {
            throw new \InvalidArgumentException('non-nullable canonical_experiments cannot be null');
        }
        $this->container['canonical_experiments'] = $canonical_experiments;

        return $this;
    }

    /**
     * Gets experiments_ingested
     *
     * @return int|null
     */
    public function getExperimentsIngested()
    {
        return $this->container['experiments_ingested'];
    }

    /**
     * Sets experiments_ingested
     *
     * @param int|null $experiments_ingested ExperimentsIngested is how many experiment versions this call appended.
     *
     * @return self
     */
    public function setExperimentsIngested($experiments_ingested)
    {
        if (is_null($experiments_ingested)) {
            throw new \InvalidArgumentException('non-nullable experiments_ingested cannot be null');
        }
        $this->container['experiments_ingested'] = $experiments_ingested;

        return $this;
    }

    /**
     * Gets experiments_retained
     *
     * @return int|null
     */
    public function getExperimentsRetained()
    {
        return $this->container['experiments_retained'];
    }

    /**
     * Sets experiments_retained
     *
     * @param int|null $experiments_retained ExperimentsRetained is the full versioned experiment history the store now holds.
     *
     * @return self
     */
    public function setExperimentsRetained($experiments_retained)
    {
        if (is_null($experiments_retained)) {
            throw new \InvalidArgumentException('non-nullable experiments_retained cannot be null');
        }
        $this->container['experiments_retained'] = $experiments_retained;

        return $this;
    }

    /**
     * Gets project
     *
     * @return string|null
     */
    public function getProject()
    {
        return $this->container['project'];
    }

    /**
     * Sets project
     *
     * @param string|null $project Project is the project the batch was filed under — the SERVER's value, never the body's.
     *
     * @return self
     */
    public function setProject($project)
    {
        if (is_null($project)) {
            throw new \InvalidArgumentException('non-nullable project cannot be null');
        }
        $this->container['project'] = $project;

        return $this;
    }

    /**
     * Gets rolled_up
     *
     * @return bool|null
     */
    public function getRolledUp()
    {
        return $this->container['rolled_up'];
    }

    /**
     * Sets rolled_up
     *
     * @param bool|null $rolled_up RolledUp is false when the OLAP roll-up was skipped; the SQLite write still stands.
     *
     * @return self
     */
    public function setRolledUp($rolled_up)
    {
        if (is_null($rolled_up)) {
            throw new \InvalidArgumentException('non-nullable rolled_up cannot be null');
        }
        $this->container['rolled_up'] = $rolled_up;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


