<?php
/**
 * O11yO11yLogPipelineOperator
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Model;

use \ArrayAccess;
use \Hanzo\Cloud\ObjectSerializer;

/**
 * O11yO11yLogPipelineOperator Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class O11yO11yLogPipelineOperator implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'o11y.O11yLogPipelineOperator';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'default' => 'string',
        'enable_flattening' => 'bool',
        'enable_paths' => 'bool',
        'enabled' => 'bool',
        'expr' => 'string',
        'field' => 'string',
        'fields' => 'string[]',
        'from' => 'string',
        'id' => 'string',
        'if' => 'string',
        'layout' => 'string',
        'layout_type' => 'string',
        'mapping' => 'array<string,string[]>',
        'name' => 'string',
        'on_error' => 'string',
        'order_id' => 'int',
        'output' => 'string',
        'overwrite_text' => 'bool',
        'parse_from' => 'string',
        'parse_to' => 'string',
        'path_prefix' => 'string',
        'pattern' => 'string',
        'regex' => 'string',
        'routes' => '\Hanzo\Cloud\Model\O11yO11yLogPipelineRoute[]',
        'span_id' => '\Hanzo\Cloud\Model\O11yO11yLogParseFrom',
        'to' => 'string',
        'trace_flags' => '\Hanzo\Cloud\Model\O11yO11yLogParseFrom',
        'trace_id' => '\Hanzo\Cloud\Model\O11yO11yLogParseFrom',
        'type' => 'string',
        'value' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'default' => null,
        'enable_flattening' => null,
        'enable_paths' => null,
        'enabled' => null,
        'expr' => null,
        'field' => null,
        'fields' => null,
        'from' => null,
        'id' => null,
        'if' => null,
        'layout' => null,
        'layout_type' => null,
        'mapping' => null,
        'name' => null,
        'on_error' => null,
        'order_id' => null,
        'output' => null,
        'overwrite_text' => null,
        'parse_from' => null,
        'parse_to' => null,
        'path_prefix' => null,
        'pattern' => null,
        'regex' => null,
        'routes' => null,
        'span_id' => null,
        'to' => null,
        'trace_flags' => null,
        'trace_id' => null,
        'type' => null,
        'value' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'default' => false,
        'enable_flattening' => false,
        'enable_paths' => false,
        'enabled' => false,
        'expr' => false,
        'field' => false,
        'fields' => false,
        'from' => false,
        'id' => false,
        'if' => false,
        'layout' => false,
        'layout_type' => false,
        'mapping' => false,
        'name' => false,
        'on_error' => false,
        'order_id' => false,
        'output' => false,
        'overwrite_text' => false,
        'parse_from' => false,
        'parse_to' => false,
        'path_prefix' => false,
        'pattern' => false,
        'regex' => false,
        'routes' => false,
        'span_id' => false,
        'to' => false,
        'trace_flags' => false,
        'trace_id' => false,
        'type' => false,
        'value' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default' => 'default',
        'enable_flattening' => 'enable_flattening',
        'enable_paths' => 'enable_paths',
        'enabled' => 'enabled',
        'expr' => 'expr',
        'field' => 'field',
        'fields' => 'fields',
        'from' => 'from',
        'id' => 'id',
        'if' => 'if',
        'layout' => 'layout',
        'layout_type' => 'layout_type',
        'mapping' => 'mapping',
        'name' => 'name',
        'on_error' => 'on_error',
        'order_id' => 'orderId',
        'output' => 'output',
        'overwrite_text' => 'overwrite_text',
        'parse_from' => 'parse_from',
        'parse_to' => 'parse_to',
        'path_prefix' => 'path_prefix',
        'pattern' => 'pattern',
        'regex' => 'regex',
        'routes' => 'routes',
        'span_id' => 'span_id',
        'to' => 'to',
        'trace_flags' => 'trace_flags',
        'trace_id' => 'trace_id',
        'type' => 'type',
        'value' => 'value'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default' => 'setDefault',
        'enable_flattening' => 'setEnableFlattening',
        'enable_paths' => 'setEnablePaths',
        'enabled' => 'setEnabled',
        'expr' => 'setExpr',
        'field' => 'setField',
        'fields' => 'setFields',
        'from' => 'setFrom',
        'id' => 'setId',
        'if' => 'setIf',
        'layout' => 'setLayout',
        'layout_type' => 'setLayoutType',
        'mapping' => 'setMapping',
        'name' => 'setName',
        'on_error' => 'setOnError',
        'order_id' => 'setOrderId',
        'output' => 'setOutput',
        'overwrite_text' => 'setOverwriteText',
        'parse_from' => 'setParseFrom',
        'parse_to' => 'setParseTo',
        'path_prefix' => 'setPathPrefix',
        'pattern' => 'setPattern',
        'regex' => 'setRegex',
        'routes' => 'setRoutes',
        'span_id' => 'setSpanId',
        'to' => 'setTo',
        'trace_flags' => 'setTraceFlags',
        'trace_id' => 'setTraceId',
        'type' => 'setType',
        'value' => 'setValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default' => 'getDefault',
        'enable_flattening' => 'getEnableFlattening',
        'enable_paths' => 'getEnablePaths',
        'enabled' => 'getEnabled',
        'expr' => 'getExpr',
        'field' => 'getField',
        'fields' => 'getFields',
        'from' => 'getFrom',
        'id' => 'getId',
        'if' => 'getIf',
        'layout' => 'getLayout',
        'layout_type' => 'getLayoutType',
        'mapping' => 'getMapping',
        'name' => 'getName',
        'on_error' => 'getOnError',
        'order_id' => 'getOrderId',
        'output' => 'getOutput',
        'overwrite_text' => 'getOverwriteText',
        'parse_from' => 'getParseFrom',
        'parse_to' => 'getParseTo',
        'path_prefix' => 'getPathPrefix',
        'pattern' => 'getPattern',
        'regex' => 'getRegex',
        'routes' => 'getRoutes',
        'span_id' => 'getSpanId',
        'to' => 'getTo',
        'trace_flags' => 'getTraceFlags',
        'trace_id' => 'getTraceId',
        'type' => 'getType',
        'value' => 'getValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('default', $data ?? [], null);
        $this->setIfExists('enable_flattening', $data ?? [], null);
        $this->setIfExists('enable_paths', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('expr', $data ?? [], null);
        $this->setIfExists('field', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('if', $data ?? [], null);
        $this->setIfExists('layout', $data ?? [], null);
        $this->setIfExists('layout_type', $data ?? [], null);
        $this->setIfExists('mapping', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('on_error', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('output', $data ?? [], null);
        $this->setIfExists('overwrite_text', $data ?? [], null);
        $this->setIfExists('parse_from', $data ?? [], null);
        $this->setIfExists('parse_to', $data ?? [], null);
        $this->setIfExists('path_prefix', $data ?? [], null);
        $this->setIfExists('pattern', $data ?? [], null);
        $this->setIfExists('regex', $data ?? [], null);
        $this->setIfExists('routes', $data ?? [], null);
        $this->setIfExists('span_id', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('trace_flags', $data ?? [], null);
        $this->setIfExists('trace_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets default
     *
     * @return string|null
     */
    public function getDefault()
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param string|null $default Default is the id of the processor a router falls through to.
     *
     * @return self
     */
    public function setDefault($default)
    {
        if (is_null($default)) {
            throw new \InvalidArgumentException('non-nullable default cannot be null');
        }
        $this->container['default'] = $default;

        return $this;
    }

    /**
     * Gets enable_flattening
     *
     * @return bool|null
     */
    public function getEnableFlattening()
    {
        return $this->container['enable_flattening'];
    }

    /**
     * Sets enable_flattening
     *
     * @param bool|null $enable_flattening EnableFlattening flattens parsed JSON one level when true.
     *
     * @return self
     */
    public function setEnableFlattening($enable_flattening)
    {
        if (is_null($enable_flattening)) {
            throw new \InvalidArgumentException('non-nullable enable_flattening cannot be null');
        }
        $this->container['enable_flattening'] = $enable_flattening;

        return $this;
    }

    /**
     * Gets enable_paths
     *
     * @return bool|null
     */
    public function getEnablePaths()
    {
        return $this->container['enable_paths'];
    }

    /**
     * Sets enable_paths
     *
     * @param bool|null $enable_paths EnablePaths keeps the JSON path in flattened keys when true.
     *
     * @return self
     */
    public function setEnablePaths($enable_paths)
    {
        if (is_null($enable_paths)) {
            throw new \InvalidArgumentException('non-nullable enable_paths cannot be null');
        }
        $this->container['enable_paths'] = $enable_paths;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled Enabled turns the processor on.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets expr
     *
     * @return string|null
     */
    public function getExpr()
    {
        return $this->container['expr'];
    }

    /**
     * Sets expr
     *
     * @param string|null $expr Expr is a router route's expression.
     *
     * @return self
     */
    public function setExpr($expr)
    {
        if (is_null($expr)) {
            throw new \InvalidArgumentException('non-nullable expr cannot be null');
        }
        $this->container['expr'] = $expr;

        return $this;
    }

    /**
     * Gets field
     *
     * @return string|null
     */
    public function getField()
    {
        return $this->container['field'];
    }

    /**
     * Sets field
     *
     * @param string|null $field Field is the field an add/remove processor works on.
     *
     * @return self
     */
    public function setField($field)
    {
        if (is_null($field)) {
            throw new \InvalidArgumentException('non-nullable field cannot be null');
        }
        $this->container['field'] = $field;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return string[]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param string[]|null $fields Fields are the fields a retain processor keeps.
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            throw new \InvalidArgumentException('non-nullable fields cannot be null');
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string|null $from From is the source field of a move or copy.
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id ID is the processor's id, unique within the pipeline.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets if
     *
     * @return string|null
     */
    public function getIf()
    {
        return $this->container['if'];
    }

    /**
     * Sets if
     *
     * @param string|null $if If gates the processor on an expression.
     *
     * @return self
     */
    public function setIf($if)
    {
        if (is_null($if)) {
            throw new \InvalidArgumentException('non-nullable if cannot be null');
        }
        $this->container['if'] = $if;

        return $this;
    }

    /**
     * Gets layout
     *
     * @return string|null
     */
    public function getLayout()
    {
        return $this->container['layout'];
    }

    /**
     * Sets layout
     *
     * @param string|null $layout Layout is a time parser's layout.
     *
     * @return self
     */
    public function setLayout($layout)
    {
        if (is_null($layout)) {
            throw new \InvalidArgumentException('non-nullable layout cannot be null');
        }
        $this->container['layout'] = $layout;

        return $this;
    }

    /**
     * Gets layout_type
     *
     * @return string|null
     */
    public function getLayoutType()
    {
        return $this->container['layout_type'];
    }

    /**
     * Sets layout_type
     *
     * @param string|null $layout_type LayoutType is the layout's kind, e.g. strptime, gotime, epoch.
     *
     * @return self
     */
    public function setLayoutType($layout_type)
    {
        if (is_null($layout_type)) {
            throw new \InvalidArgumentException('non-nullable layout_type cannot be null');
        }
        $this->container['layout_type'] = $layout_type;

        return $this;
    }

    /**
     * Gets mapping
     *
     * @return array<string,string[]>|null
     */
    public function getMapping()
    {
        return $this->container['mapping'];
    }

    /**
     * Sets mapping
     *
     * @param array<string,string[]>|null $mapping Mapping maps severity levels (or flattened keys) to the values that mean them.
     *
     * @return self
     */
    public function setMapping($mapping)
    {
        if (is_null($mapping)) {
            throw new \InvalidArgumentException('non-nullable mapping cannot be null');
        }
        $this->container['mapping'] = $mapping;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Name is the processor's display name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets on_error
     *
     * @return string|null
     */
    public function getOnError()
    {
        return $this->container['on_error'];
    }

    /**
     * Sets on_error
     *
     * @param string|null $on_error OnError says what to do when the processor fails, e.g. send, drop.
     *
     * @return self
     */
    public function setOnError($on_error)
    {
        if (is_null($on_error)) {
            throw new \InvalidArgumentException('non-nullable on_error cannot be null');
        }
        $this->container['on_error'] = $on_error;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return int|null
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param int|null $order_id OrderID is the processor's 1-based position in the pipeline.
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            throw new \InvalidArgumentException('non-nullable order_id cannot be null');
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets output
     *
     * @return string|null
     */
    public function getOutput()
    {
        return $this->container['output'];
    }

    /**
     * Sets output
     *
     * @param string|null $output Output is the id of the processor that runs next.
     *
     * @return self
     */
    public function setOutput($output)
    {
        if (is_null($output)) {
            throw new \InvalidArgumentException('non-nullable output cannot be null');
        }
        $this->container['output'] = $output;

        return $this;
    }

    /**
     * Gets overwrite_text
     *
     * @return bool|null
     */
    public function getOverwriteText()
    {
        return $this->container['overwrite_text'];
    }

    /**
     * Sets overwrite_text
     *
     * @param bool|null $overwrite_text OverwriteSeverityText rewrites the severity text alongside the number when true.
     *
     * @return self
     */
    public function setOverwriteText($overwrite_text)
    {
        if (is_null($overwrite_text)) {
            throw new \InvalidArgumentException('non-nullable overwrite_text cannot be null');
        }
        $this->container['overwrite_text'] = $overwrite_text;

        return $this;
    }

    /**
     * Gets parse_from
     *
     * @return string|null
     */
    public function getParseFrom()
    {
        return $this->container['parse_from'];
    }

    /**
     * Sets parse_from
     *
     * @param string|null $parse_from ParseFrom is where a parser reads from.
     *
     * @return self
     */
    public function setParseFrom($parse_from)
    {
        if (is_null($parse_from)) {
            throw new \InvalidArgumentException('non-nullable parse_from cannot be null');
        }
        $this->container['parse_from'] = $parse_from;

        return $this;
    }

    /**
     * Gets parse_to
     *
     * @return string|null
     */
    public function getParseTo()
    {
        return $this->container['parse_to'];
    }

    /**
     * Sets parse_to
     *
     * @param string|null $parse_to ParseTo is where a parser writes its result.
     *
     * @return self
     */
    public function setParseTo($parse_to)
    {
        if (is_null($parse_to)) {
            throw new \InvalidArgumentException('non-nullable parse_to cannot be null');
        }
        $this->container['parse_to'] = $parse_to;

        return $this;
    }

    /**
     * Gets path_prefix
     *
     * @return string|null
     */
    public function getPathPrefix()
    {
        return $this->container['path_prefix'];
    }

    /**
     * Sets path_prefix
     *
     * @param string|null $path_prefix PathPrefix prefixes flattened keys.
     *
     * @return self
     */
    public function setPathPrefix($path_prefix)
    {
        if (is_null($path_prefix)) {
            throw new \InvalidArgumentException('non-nullable path_prefix cannot be null');
        }
        $this->container['path_prefix'] = $path_prefix;

        return $this;
    }

    /**
     * Gets pattern
     *
     * @return string|null
     */
    public function getPattern()
    {
        return $this->container['pattern'];
    }

    /**
     * Sets pattern
     *
     * @param string|null $pattern Pattern is a grok parser's pattern.
     *
     * @return self
     */
    public function setPattern($pattern)
    {
        if (is_null($pattern)) {
            throw new \InvalidArgumentException('non-nullable pattern cannot be null');
        }
        $this->container['pattern'] = $pattern;

        return $this;
    }

    /**
     * Gets regex
     *
     * @return string|null
     */
    public function getRegex()
    {
        return $this->container['regex'];
    }

    /**
     * Sets regex
     *
     * @param string|null $regex Regex is a regex parser's expression.
     *
     * @return self
     */
    public function setRegex($regex)
    {
        if (is_null($regex)) {
            throw new \InvalidArgumentException('non-nullable regex cannot be null');
        }
        $this->container['regex'] = $regex;

        return $this;
    }

    /**
     * Gets routes
     *
     * @return \Hanzo\Cloud\Model\O11yO11yLogPipelineRoute[]|null
     */
    public function getRoutes()
    {
        return $this->container['routes'];
    }

    /**
     * Sets routes
     *
     * @param \Hanzo\Cloud\Model\O11yO11yLogPipelineRoute[]|null $routes Routes are a router processor's routes.
     *
     * @return self
     */
    public function setRoutes($routes)
    {
        if (is_null($routes)) {
            throw new \InvalidArgumentException('non-nullable routes cannot be null');
        }
        $this->container['routes'] = $routes;

        return $this;
    }

    /**
     * Gets span_id
     *
     * @return \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null
     */
    public function getSpanId()
    {
        return $this->container['span_id'];
    }

    /**
     * Sets span_id
     *
     * @param \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null $span_id SpanID says where a trace parser reads the span id from.
     *
     * @return self
     */
    public function setSpanId($span_id)
    {
        if (is_null($span_id)) {
            throw new \InvalidArgumentException('non-nullable span_id cannot be null');
        }
        $this->container['span_id'] = $span_id;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string|null $to To is the destination field of a move or copy.
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets trace_flags
     *
     * @return \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null
     */
    public function getTraceFlags()
    {
        return $this->container['trace_flags'];
    }

    /**
     * Sets trace_flags
     *
     * @param \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null $trace_flags TraceFlags says where a trace parser reads the trace flags from.
     *
     * @return self
     */
    public function setTraceFlags($trace_flags)
    {
        if (is_null($trace_flags)) {
            throw new \InvalidArgumentException('non-nullable trace_flags cannot be null');
        }
        $this->container['trace_flags'] = $trace_flags;

        return $this;
    }

    /**
     * Gets trace_id
     *
     * @return \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null
     */
    public function getTraceId()
    {
        return $this->container['trace_id'];
    }

    /**
     * Sets trace_id
     *
     * @param \Hanzo\Cloud\Model\O11yO11yLogParseFrom|null $trace_id TraceID says where a trace parser reads the trace id from.
     *
     * @return self
     */
    public function setTraceId($trace_id)
    {
        if (is_null($trace_id)) {
            throw new \InvalidArgumentException('non-nullable trace_id cannot be null');
        }
        $this->container['trace_id'] = $trace_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type Type is the processor type, e.g. grok_parser, regex_parser, json_parser, trace_parser, time_parser, severity_parser, add, remove, move, copy.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string|null $value Value is the value an add processor writes.
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


