<?php
/**
 * O11yGettableWaterfallTrace
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Model;

use \ArrayAccess;
use \Hanzo\Cloud\ObjectSerializer;

/**
 * O11yGettableWaterfallTrace Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class O11yGettableWaterfallTrace implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'o11y.GettableWaterfallTrace';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'end_timestamp_millis' => 'int',
        'has_missing_spans' => 'bool',
        'has_more' => 'bool',
        'root_service_entry_point' => 'string',
        'root_service_name' => 'string',
        'spans' => '\Hanzo\Cloud\Model\O11yWaterfallSpan[]',
        'start_timestamp_millis' => 'int',
        'total_error_spans_count' => 'int',
        'total_spans_count' => 'int',
        'uncollapsed_spans' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'end_timestamp_millis' => null,
        'has_missing_spans' => null,
        'has_more' => null,
        'root_service_entry_point' => null,
        'root_service_name' => null,
        'spans' => null,
        'start_timestamp_millis' => null,
        'total_error_spans_count' => null,
        'total_spans_count' => null,
        'uncollapsed_spans' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'end_timestamp_millis' => false,
        'has_missing_spans' => false,
        'has_more' => false,
        'root_service_entry_point' => false,
        'root_service_name' => false,
        'spans' => false,
        'start_timestamp_millis' => false,
        'total_error_spans_count' => false,
        'total_spans_count' => false,
        'uncollapsed_spans' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'end_timestamp_millis' => 'endTimestampMillis',
        'has_missing_spans' => 'hasMissingSpans',
        'has_more' => 'hasMore',
        'root_service_entry_point' => 'rootServiceEntryPoint',
        'root_service_name' => 'rootServiceName',
        'spans' => 'spans',
        'start_timestamp_millis' => 'startTimestampMillis',
        'total_error_spans_count' => 'totalErrorSpansCount',
        'total_spans_count' => 'totalSpansCount',
        'uncollapsed_spans' => 'uncollapsedSpans'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'end_timestamp_millis' => 'setEndTimestampMillis',
        'has_missing_spans' => 'setHasMissingSpans',
        'has_more' => 'setHasMore',
        'root_service_entry_point' => 'setRootServiceEntryPoint',
        'root_service_name' => 'setRootServiceName',
        'spans' => 'setSpans',
        'start_timestamp_millis' => 'setStartTimestampMillis',
        'total_error_spans_count' => 'setTotalErrorSpansCount',
        'total_spans_count' => 'setTotalSpansCount',
        'uncollapsed_spans' => 'setUncollapsedSpans'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'end_timestamp_millis' => 'getEndTimestampMillis',
        'has_missing_spans' => 'getHasMissingSpans',
        'has_more' => 'getHasMore',
        'root_service_entry_point' => 'getRootServiceEntryPoint',
        'root_service_name' => 'getRootServiceName',
        'spans' => 'getSpans',
        'start_timestamp_millis' => 'getStartTimestampMillis',
        'total_error_spans_count' => 'getTotalErrorSpansCount',
        'total_spans_count' => 'getTotalSpansCount',
        'uncollapsed_spans' => 'getUncollapsedSpans'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('end_timestamp_millis', $data ?? [], null);
        $this->setIfExists('has_missing_spans', $data ?? [], null);
        $this->setIfExists('has_more', $data ?? [], null);
        $this->setIfExists('root_service_entry_point', $data ?? [], null);
        $this->setIfExists('root_service_name', $data ?? [], null);
        $this->setIfExists('spans', $data ?? [], null);
        $this->setIfExists('start_timestamp_millis', $data ?? [], null);
        $this->setIfExists('total_error_spans_count', $data ?? [], null);
        $this->setIfExists('total_spans_count', $data ?? [], null);
        $this->setIfExists('uncollapsed_spans', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets end_timestamp_millis
     *
     * @return int|null
     */
    public function getEndTimestampMillis()
    {
        return $this->container['end_timestamp_millis'];
    }

    /**
     * Sets end_timestamp_millis
     *
     * @param int|null $end_timestamp_millis end_timestamp_millis
     *
     * @return self
     */
    public function setEndTimestampMillis($end_timestamp_millis)
    {
        if (is_null($end_timestamp_millis)) {
            throw new \InvalidArgumentException('non-nullable end_timestamp_millis cannot be null');
        }
        $this->container['end_timestamp_millis'] = $end_timestamp_millis;

        return $this;
    }

    /**
     * Gets has_missing_spans
     *
     * @return bool|null
     */
    public function getHasMissingSpans()
    {
        return $this->container['has_missing_spans'];
    }

    /**
     * Sets has_missing_spans
     *
     * @param bool|null $has_missing_spans has_missing_spans
     *
     * @return self
     */
    public function setHasMissingSpans($has_missing_spans)
    {
        if (is_null($has_missing_spans)) {
            throw new \InvalidArgumentException('non-nullable has_missing_spans cannot be null');
        }
        $this->container['has_missing_spans'] = $has_missing_spans;

        return $this;
    }

    /**
     * Gets has_more
     *
     * @return bool|null
     */
    public function getHasMore()
    {
        return $this->container['has_more'];
    }

    /**
     * Sets has_more
     *
     * @param bool|null $has_more has_more
     *
     * @return self
     */
    public function setHasMore($has_more)
    {
        if (is_null($has_more)) {
            throw new \InvalidArgumentException('non-nullable has_more cannot be null');
        }
        $this->container['has_more'] = $has_more;

        return $this;
    }

    /**
     * Gets root_service_entry_point
     *
     * @return string|null
     */
    public function getRootServiceEntryPoint()
    {
        return $this->container['root_service_entry_point'];
    }

    /**
     * Sets root_service_entry_point
     *
     * @param string|null $root_service_entry_point root_service_entry_point
     *
     * @return self
     */
    public function setRootServiceEntryPoint($root_service_entry_point)
    {
        if (is_null($root_service_entry_point)) {
            throw new \InvalidArgumentException('non-nullable root_service_entry_point cannot be null');
        }
        $this->container['root_service_entry_point'] = $root_service_entry_point;

        return $this;
    }

    /**
     * Gets root_service_name
     *
     * @return string|null
     */
    public function getRootServiceName()
    {
        return $this->container['root_service_name'];
    }

    /**
     * Sets root_service_name
     *
     * @param string|null $root_service_name root_service_name
     *
     * @return self
     */
    public function setRootServiceName($root_service_name)
    {
        if (is_null($root_service_name)) {
            throw new \InvalidArgumentException('non-nullable root_service_name cannot be null');
        }
        $this->container['root_service_name'] = $root_service_name;

        return $this;
    }

    /**
     * Gets spans
     *
     * @return \Hanzo\Cloud\Model\O11yWaterfallSpan[]|null
     */
    public function getSpans()
    {
        return $this->container['spans'];
    }

    /**
     * Sets spans
     *
     * @param \Hanzo\Cloud\Model\O11yWaterfallSpan[]|null $spans spans
     *
     * @return self
     */
    public function setSpans($spans)
    {
        if (is_null($spans)) {
            throw new \InvalidArgumentException('non-nullable spans cannot be null');
        }
        $this->container['spans'] = $spans;

        return $this;
    }

    /**
     * Gets start_timestamp_millis
     *
     * @return int|null
     */
    public function getStartTimestampMillis()
    {
        return $this->container['start_timestamp_millis'];
    }

    /**
     * Sets start_timestamp_millis
     *
     * @param int|null $start_timestamp_millis start_timestamp_millis
     *
     * @return self
     */
    public function setStartTimestampMillis($start_timestamp_millis)
    {
        if (is_null($start_timestamp_millis)) {
            throw new \InvalidArgumentException('non-nullable start_timestamp_millis cannot be null');
        }
        $this->container['start_timestamp_millis'] = $start_timestamp_millis;

        return $this;
    }

    /**
     * Gets total_error_spans_count
     *
     * @return int|null
     */
    public function getTotalErrorSpansCount()
    {
        return $this->container['total_error_spans_count'];
    }

    /**
     * Sets total_error_spans_count
     *
     * @param int|null $total_error_spans_count total_error_spans_count
     *
     * @return self
     */
    public function setTotalErrorSpansCount($total_error_spans_count)
    {
        if (is_null($total_error_spans_count)) {
            throw new \InvalidArgumentException('non-nullable total_error_spans_count cannot be null');
        }
        $this->container['total_error_spans_count'] = $total_error_spans_count;

        return $this;
    }

    /**
     * Gets total_spans_count
     *
     * @return int|null
     */
    public function getTotalSpansCount()
    {
        return $this->container['total_spans_count'];
    }

    /**
     * Sets total_spans_count
     *
     * @param int|null $total_spans_count total_spans_count
     *
     * @return self
     */
    public function setTotalSpansCount($total_spans_count)
    {
        if (is_null($total_spans_count)) {
            throw new \InvalidArgumentException('non-nullable total_spans_count cannot be null');
        }
        $this->container['total_spans_count'] = $total_spans_count;

        return $this;
    }

    /**
     * Gets uncollapsed_spans
     *
     * @return string[]|null
     */
    public function getUncollapsedSpans()
    {
        return $this->container['uncollapsed_spans'];
    }

    /**
     * Sets uncollapsed_spans
     *
     * @param string[]|null $uncollapsed_spans uncollapsed_spans
     *
     * @return self
     */
    public function setUncollapsedSpans($uncollapsed_spans)
    {
        if (is_null($uncollapsed_spans)) {
            throw new \InvalidArgumentException('non-nullable uncollapsed_spans cannot be null');
        }
        $this->container['uncollapsed_spans'] = $uncollapsed_spans;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


