<?php
/**
 * RiskLineage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Model;

use \ArrayAccess;
use \Hanzo\Cloud\ObjectSerializer;

/**
 * RiskLineage Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RiskLineage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'riskLineage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'dataset' => 'string',
        'digest' => 'string',
        'from' => 'string',
        'holds' => 'int',
        'oversize' => 'int',
        'refusal' => 'string',
        'reproducible' => 'bool',
        'retention' => 'string',
        'rows' => 'int',
        'share' => 'int',
        'source' => 'string',
        'subjects' => 'int',
        'to' => 'string',
        'version' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'dataset' => null,
        'digest' => null,
        'from' => null,
        'holds' => null,
        'oversize' => null,
        'refusal' => null,
        'reproducible' => null,
        'retention' => null,
        'rows' => null,
        'share' => null,
        'source' => null,
        'subjects' => null,
        'to' => null,
        'version' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'dataset' => false,
        'digest' => false,
        'from' => false,
        'holds' => false,
        'oversize' => false,
        'refusal' => false,
        'reproducible' => false,
        'retention' => false,
        'rows' => false,
        'share' => false,
        'source' => false,
        'subjects' => false,
        'to' => false,
        'version' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dataset' => 'dataset',
        'digest' => 'digest',
        'from' => 'from',
        'holds' => 'holds',
        'oversize' => 'oversize',
        'refusal' => 'refusal',
        'reproducible' => 'reproducible',
        'retention' => 'retention',
        'rows' => 'rows',
        'share' => 'share',
        'source' => 'source',
        'subjects' => 'subjects',
        'to' => 'to',
        'version' => 'version'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dataset' => 'setDataset',
        'digest' => 'setDigest',
        'from' => 'setFrom',
        'holds' => 'setHolds',
        'oversize' => 'setOversize',
        'refusal' => 'setRefusal',
        'reproducible' => 'setReproducible',
        'retention' => 'setRetention',
        'rows' => 'setRows',
        'share' => 'setShare',
        'source' => 'setSource',
        'subjects' => 'setSubjects',
        'to' => 'setTo',
        'version' => 'setVersion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dataset' => 'getDataset',
        'digest' => 'getDigest',
        'from' => 'getFrom',
        'holds' => 'getHolds',
        'oversize' => 'getOversize',
        'refusal' => 'getRefusal',
        'reproducible' => 'getReproducible',
        'retention' => 'getRetention',
        'rows' => 'getRows',
        'share' => 'getShare',
        'source' => 'getSource',
        'subjects' => 'getSubjects',
        'to' => 'getTo',
        'version' => 'getVersion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('dataset', $data ?? [], null);
        $this->setIfExists('digest', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('holds', $data ?? [], null);
        $this->setIfExists('oversize', $data ?? [], null);
        $this->setIfExists('refusal', $data ?? [], null);
        $this->setIfExists('reproducible', $data ?? [], null);
        $this->setIfExists('retention', $data ?? [], null);
        $this->setIfExists('rows', $data ?? [], null);
        $this->setIfExists('share', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('subjects', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dataset
     *
     * @return string|null
     */
    public function getDataset()
    {
        return $this->container['dataset'];
    }

    /**
     * Sets dataset
     *
     * @param string|null $dataset Dataset is the dataset traced.
     *
     * @return self
     */
    public function setDataset($dataset)
    {
        if (is_null($dataset)) {
            throw new \InvalidArgumentException('non-nullable dataset cannot be null');
        }
        $this->container['dataset'] = $dataset;

        return $this;
    }

    /**
     * Gets digest
     *
     * @return string|null
     */
    public function getDigest()
    {
        return $this->container['digest'];
    }

    /**
     * Sets digest
     *
     * @param string|null $digest Digest is the version's fingerprint, repeated here so a lineage answer is self-contained.
     *
     * @return self
     */
    public function setDigest($digest)
    {
        if (is_null($digest)) {
            throw new \InvalidArgumentException('non-nullable digest cannot be null');
        }
        $this->container['digest'] = $digest;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string|null $from From is where the window actually read opens, RFC 3339. Same as the spec's.
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets holds
     *
     * @return int|null
     */
    public function getHolds()
    {
        return $this->container['holds'];
    }

    /**
     * Sets holds
     *
     * @param int|null $holds Holds is what the source holds for the same window NOW. The difference between it and Rows is the whole of the reproducibility claim.
     *
     * @return self
     */
    public function setHolds($holds)
    {
        if (is_null($holds)) {
            throw new \InvalidArgumentException('non-nullable holds cannot be null');
        }
        $this->container['holds'] = $holds;

        return $this;
    }

    /**
     * Gets oversize
     *
     * @return int|null
     */
    public function getOversize()
    {
        return $this->container['oversize'];
    }

    /**
     * Sets oversize
     *
     * @param int|null $oversize Oversize is how many subjects the window held that were too large to represent when this version was built. It is part of the fingerprint, so it is part of what \"reproducible\" is measured over.
     *
     * @return self
     */
    public function setOversize($oversize)
    {
        if (is_null($oversize)) {
            throw new \InvalidArgumentException('non-nullable oversize cannot be null');
        }
        $this->container['oversize'] = $oversize;

        return $this;
    }

    /**
     * Gets refusal
     *
     * @return string|null
     */
    public function getRefusal()
    {
        return $this->container['refusal'];
    }

    /**
     * Sets refusal
     *
     * @param string|null $refusal Refusal says which way it failed — the window expired, or the source now holds a different count. Absent when Reproducible is true.
     *
     * @return self
     */
    public function setRefusal($refusal)
    {
        if (is_null($refusal)) {
            throw new \InvalidArgumentException('non-nullable refusal cannot be null');
        }
        $this->container['refusal'] = $refusal;

        return $this;
    }

    /**
     * Gets reproducible
     *
     * @return bool|null
     */
    public function getReproducible()
    {
        return $this->container['reproducible'];
    }

    /**
     * Sets reproducible
     *
     * @param bool|null $reproducible Reproducible is true when the source still holds what this version was built from — measured by asking it again, not recalled. False is ordinary: the source is fed by a rollup that runs behind the events, so \"it holds more now\" is the common case and it means re-running the spec would not produce this version.
     *
     * @return self
     */
    public function setReproducible($reproducible)
    {
        if (is_null($reproducible)) {
            throw new \InvalidArgumentException('non-nullable reproducible cannot be null');
        }
        $this->container['reproducible'] = $reproducible;

        return $this;
    }

    /**
     * Gets retention
     *
     * @return string|null
     */
    public function getRetention()
    {
        return $this->container['retention'];
    }

    /**
     * Sets retention
     *
     * @param string|null $retention Retention is the source's own expiry rule as the store reports it, read at materialisation time rather than assumed. A source whose retention is shorter than this window cannot re-derive it.
     *
     * @return self
     */
    public function setRetention($retention)
    {
        if (is_null($retention)) {
            throw new \InvalidArgumentException('non-nullable retention cannot be null');
        }
        $this->container['retention'] = $retention;

        return $this;
    }

    /**
     * Gets rows
     *
     * @return int|null
     */
    public function getRows()
    {
        return $this->container['rows'];
    }

    /**
     * Sets rows
     *
     * @param int|null $rows Rows is how many rows the source held for that window at materialisation time. Holds is the same question asked now, and the difference between them is the whole of the reproducibility claim.
     *
     * @return self
     */
    public function setRows($rows)
    {
        if (is_null($rows)) {
            throw new \InvalidArgumentException('non-nullable rows cannot be null');
        }
        $this->container['rows'] = $rows;

        return $this;
    }

    /**
     * Gets share
     *
     * @return int|null
     */
    public function getShare()
    {
        return $this->container['share'];
    }

    /**
     * Sets share
     *
     * @param int|null $share Share is the fraction of subjects admitted, in thousandths.
     *
     * @return self
     */
    public function setShare($share)
    {
        if (is_null($share)) {
            throw new \InvalidArgumentException('non-nullable share cannot be null');
        }
        $this->container['share'] = $share;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source Source is the plane the rows were derived from.
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets subjects
     *
     * @return int|null
     */
    public function getSubjects()
    {
        return $this->container['subjects'];
    }

    /**
     * Sets subjects
     *
     * @param int|null $subjects Subjects is how many distinct subjects those rows belonged to. It is the real sample size — the row count flatters it whenever a subject is active.
     *
     * @return self
     */
    public function setSubjects($subjects)
    {
        if (is_null($subjects)) {
            throw new \InvalidArgumentException('non-nullable subjects cannot be null');
        }
        $this->container['subjects'] = $subjects;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string|null $to To is where it ends: the spec's own end pulled BACK by the maturity horizon, so it is usually earlier than the spec says. This is the window a reproduction has to ask for — asking the spec's would not return these rows.
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int|null $version Version is the version traced — the one asked for, or the newest published one when the request named none.
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


