<?php
/**
 * DatasetApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Hanzo\Cloud\ApiException;
use Hanzo\Cloud\Configuration;
use Hanzo\Cloud\FormDataProcessor;
use Hanzo\Cloud\HeaderSelector;
use Hanzo\Cloud\ObjectSerializer;

/**
 * DatasetApi Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DatasetApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'riskCreateDataset' => [
            'application/json',
        ],
        'riskDataset' => [
            'application/json',
        ],
        'riskDatasetLineage' => [
            'application/json',
        ],
        'riskDatasets' => [
            'application/json',
        ],
        'riskDeleteDataset' => [
            'application/json',
        ],
        'riskExportDataset' => [
            'application/json',
        ],
        'riskMaterializeDataset' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation riskCreateDataset
     *
     * Declare the next version of a dataset
     *
     * @param  \Hanzo\Cloud\Model\RiskDatasetSpec $risk_dataset_spec risk_dataset_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskCreateDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDataset
     */
    public function riskCreateDataset($risk_dataset_spec, string $contentType = self::contentTypes['riskCreateDataset'][0])
    {
        list($response) = $this->riskCreateDatasetWithHttpInfo($risk_dataset_spec, $contentType);
        return $response;
    }

    /**
     * Operation riskCreateDatasetWithHttpInfo
     *
     * Declare the next version of a dataset
     *
     * @param  \Hanzo\Cloud\Model\RiskDatasetSpec $risk_dataset_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskCreateDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDataset, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskCreateDatasetWithHttpInfo($risk_dataset_spec, string $contentType = self::contentTypes['riskCreateDataset'][0])
    {
        $request = $this->riskCreateDatasetRequest($risk_dataset_spec, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDataset',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDataset',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDataset',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskCreateDatasetAsync
     *
     * Declare the next version of a dataset
     *
     * @param  \Hanzo\Cloud\Model\RiskDatasetSpec $risk_dataset_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskCreateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskCreateDatasetAsync($risk_dataset_spec, string $contentType = self::contentTypes['riskCreateDataset'][0])
    {
        return $this->riskCreateDatasetAsyncWithHttpInfo($risk_dataset_spec, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskCreateDatasetAsyncWithHttpInfo
     *
     * Declare the next version of a dataset
     *
     * @param  \Hanzo\Cloud\Model\RiskDatasetSpec $risk_dataset_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskCreateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskCreateDatasetAsyncWithHttpInfo($risk_dataset_spec, string $contentType = self::contentTypes['riskCreateDataset'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDataset';
        $request = $this->riskCreateDatasetRequest($risk_dataset_spec, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskCreateDataset'
     *
     * @param  \Hanzo\Cloud\Model\RiskDatasetSpec $risk_dataset_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskCreateDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskCreateDatasetRequest($risk_dataset_spec, string $contentType = self::contentTypes['riskCreateDataset'][0])
    {

        // verify the required parameter 'risk_dataset_spec' is set
        if ($risk_dataset_spec === null || (is_array($risk_dataset_spec) && count($risk_dataset_spec) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $risk_dataset_spec when calling riskCreateDataset'
            );
        }


        $resourcePath = '/v1/dataset';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($risk_dataset_spec)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($risk_dataset_spec));
            } else {
                $httpBody = $risk_dataset_spec;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskDataset
     *
     * Describe every version of one dataset
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDatasetVersions
     */
    public function riskDataset($name, string $contentType = self::contentTypes['riskDataset'][0])
    {
        list($response) = $this->riskDatasetWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation riskDatasetWithHttpInfo
     *
     * Describe every version of one dataset
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDatasetVersions, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskDatasetWithHttpInfo($name, string $contentType = self::contentTypes['riskDataset'][0])
    {
        $request = $this->riskDatasetRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDatasetVersions',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDatasetVersions',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDatasetVersions',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskDatasetAsync
     *
     * Describe every version of one dataset
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetAsync($name, string $contentType = self::contentTypes['riskDataset'][0])
    {
        return $this->riskDatasetAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskDatasetAsyncWithHttpInfo
     *
     * Describe every version of one dataset
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetAsyncWithHttpInfo($name, string $contentType = self::contentTypes['riskDataset'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDatasetVersions';
        $request = $this->riskDatasetRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskDataset'
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskDatasetRequest($name, string $contentType = self::contentTypes['riskDataset'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling riskDataset'
            );
        }


        $resourcePath = '/v1/dataset/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskDatasetLineage
     *
     * Show where a version&#39;s rows came from, and whether that can still be demonstrated
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to trace. Zero takes the newest published one. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasetLineage'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskLineage
     */
    public function riskDatasetLineage($name, $version = null, string $contentType = self::contentTypes['riskDatasetLineage'][0])
    {
        list($response) = $this->riskDatasetLineageWithHttpInfo($name, $version, $contentType);
        return $response;
    }

    /**
     * Operation riskDatasetLineageWithHttpInfo
     *
     * Show where a version&#39;s rows came from, and whether that can still be demonstrated
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to trace. Zero takes the newest published one. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasetLineage'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskLineage, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskDatasetLineageWithHttpInfo($name, $version = null, string $contentType = self::contentTypes['riskDatasetLineage'][0])
    {
        $request = $this->riskDatasetLineageRequest($name, $version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskLineage',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskLineage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskLineage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskDatasetLineageAsync
     *
     * Show where a version&#39;s rows came from, and whether that can still be demonstrated
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to trace. Zero takes the newest published one. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasetLineage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetLineageAsync($name, $version = null, string $contentType = self::contentTypes['riskDatasetLineage'][0])
    {
        return $this->riskDatasetLineageAsyncWithHttpInfo($name, $version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskDatasetLineageAsyncWithHttpInfo
     *
     * Show where a version&#39;s rows came from, and whether that can still be demonstrated
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to trace. Zero takes the newest published one. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasetLineage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetLineageAsyncWithHttpInfo($name, $version = null, string $contentType = self::contentTypes['riskDatasetLineage'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskLineage';
        $request = $this->riskDatasetLineageRequest($name, $version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskDatasetLineage'
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to trace. Zero takes the newest published one. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasetLineage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskDatasetLineageRequest($name, $version = null, string $contentType = self::contentTypes['riskDatasetLineage'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling riskDatasetLineage'
            );
        }



        $resourcePath = '/v1/dataset/{name}/lineage';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $version,
            'version', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskDatasets
     *
     * List this org&#39;s datasets
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasets'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDatasetList
     */
    public function riskDatasets(string $contentType = self::contentTypes['riskDatasets'][0])
    {
        list($response) = $this->riskDatasetsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation riskDatasetsWithHttpInfo
     *
     * List this org&#39;s datasets
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasets'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDatasetList, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskDatasetsWithHttpInfo(string $contentType = self::contentTypes['riskDatasets'][0])
    {
        $request = $this->riskDatasetsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDatasetList',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDatasetList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDatasetList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskDatasetsAsync
     *
     * List this org&#39;s datasets
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetsAsync(string $contentType = self::contentTypes['riskDatasets'][0])
    {
        return $this->riskDatasetsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskDatasetsAsyncWithHttpInfo
     *
     * List this org&#39;s datasets
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDatasetsAsyncWithHttpInfo(string $contentType = self::contentTypes['riskDatasets'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDatasetList';
        $request = $this->riskDatasetsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskDatasets'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDatasets'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskDatasetsRequest(string $contentType = self::contentTypes['riskDatasets'][0])
    {


        $resourcePath = '/v1/dataset';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskDeleteDataset
     *
     * Dispose of one dataset and every version of it
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDeleteDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDatasetDisposal
     */
    public function riskDeleteDataset($name, string $contentType = self::contentTypes['riskDeleteDataset'][0])
    {
        list($response) = $this->riskDeleteDatasetWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation riskDeleteDatasetWithHttpInfo
     *
     * Dispose of one dataset and every version of it
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDeleteDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDatasetDisposal, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskDeleteDatasetWithHttpInfo($name, string $contentType = self::contentTypes['riskDeleteDataset'][0])
    {
        $request = $this->riskDeleteDatasetRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDatasetDisposal',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDatasetDisposal',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDatasetDisposal',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskDeleteDatasetAsync
     *
     * Dispose of one dataset and every version of it
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDeleteDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDeleteDatasetAsync($name, string $contentType = self::contentTypes['riskDeleteDataset'][0])
    {
        return $this->riskDeleteDatasetAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskDeleteDatasetAsyncWithHttpInfo
     *
     * Dispose of one dataset and every version of it
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDeleteDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskDeleteDatasetAsyncWithHttpInfo($name, string $contentType = self::contentTypes['riskDeleteDataset'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDatasetDisposal';
        $request = $this->riskDeleteDatasetRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskDeleteDataset'
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskDeleteDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskDeleteDatasetRequest($name, string $contentType = self::contentTypes['riskDeleteDataset'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling riskDeleteDataset'
            );
        }


        $resourcePath = '/v1/dataset/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskExportDataset
     *
     * Read a version&#39;s rows back, one page at a time
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to read. Zero takes the newest published one. (optional)
     * @param  string|null $split Split narrows to train, val or test. Empty reads every split. (optional)
     * @param  int|null $offset Offset is where the page starts, in the version&#39;s own row order (by id, which is derived from the row and therefore stable forever). (optional)
     * @param  int|null $limit Limit is how many rows to return. Zero and anything above the plane&#39;s bound take the bound. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskExportDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDatasetRows
     */
    public function riskExportDataset($name, $version = null, $split = null, $offset = null, $limit = null, string $contentType = self::contentTypes['riskExportDataset'][0])
    {
        list($response) = $this->riskExportDatasetWithHttpInfo($name, $version, $split, $offset, $limit, $contentType);
        return $response;
    }

    /**
     * Operation riskExportDatasetWithHttpInfo
     *
     * Read a version&#39;s rows back, one page at a time
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to read. Zero takes the newest published one. (optional)
     * @param  string|null $split Split narrows to train, val or test. Empty reads every split. (optional)
     * @param  int|null $offset Offset is where the page starts, in the version&#39;s own row order (by id, which is derived from the row and therefore stable forever). (optional)
     * @param  int|null $limit Limit is how many rows to return. Zero and anything above the plane&#39;s bound take the bound. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskExportDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDatasetRows, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskExportDatasetWithHttpInfo($name, $version = null, $split = null, $offset = null, $limit = null, string $contentType = self::contentTypes['riskExportDataset'][0])
    {
        $request = $this->riskExportDatasetRequest($name, $version, $split, $offset, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDatasetRows',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDatasetRows',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDatasetRows',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskExportDatasetAsync
     *
     * Read a version&#39;s rows back, one page at a time
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to read. Zero takes the newest published one. (optional)
     * @param  string|null $split Split narrows to train, val or test. Empty reads every split. (optional)
     * @param  int|null $offset Offset is where the page starts, in the version&#39;s own row order (by id, which is derived from the row and therefore stable forever). (optional)
     * @param  int|null $limit Limit is how many rows to return. Zero and anything above the plane&#39;s bound take the bound. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskExportDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskExportDatasetAsync($name, $version = null, $split = null, $offset = null, $limit = null, string $contentType = self::contentTypes['riskExportDataset'][0])
    {
        return $this->riskExportDatasetAsyncWithHttpInfo($name, $version, $split, $offset, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskExportDatasetAsyncWithHttpInfo
     *
     * Read a version&#39;s rows back, one page at a time
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to read. Zero takes the newest published one. (optional)
     * @param  string|null $split Split narrows to train, val or test. Empty reads every split. (optional)
     * @param  int|null $offset Offset is where the page starts, in the version&#39;s own row order (by id, which is derived from the row and therefore stable forever). (optional)
     * @param  int|null $limit Limit is how many rows to return. Zero and anything above the plane&#39;s bound take the bound. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskExportDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskExportDatasetAsyncWithHttpInfo($name, $version = null, $split = null, $offset = null, $limit = null, string $contentType = self::contentTypes['riskExportDataset'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDatasetRows';
        $request = $this->riskExportDatasetRequest($name, $version, $split, $offset, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskExportDataset'
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  int|null $version Version is the version to read. Zero takes the newest published one. (optional)
     * @param  string|null $split Split narrows to train, val or test. Empty reads every split. (optional)
     * @param  int|null $offset Offset is where the page starts, in the version&#39;s own row order (by id, which is derived from the row and therefore stable forever). (optional)
     * @param  int|null $limit Limit is how many rows to return. Zero and anything above the plane&#39;s bound take the bound. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskExportDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskExportDatasetRequest($name, $version = null, $split = null, $offset = null, $limit = null, string $contentType = self::contentTypes['riskExportDataset'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling riskExportDataset'
            );
        }






        $resourcePath = '/v1/dataset/{name}/export';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $version,
            'version', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $split,
            'split', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation riskMaterializeDataset
     *
     * Materialise the declared version into immutable rows
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskMaterializeDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\RiskDataset
     */
    public function riskMaterializeDataset($name, string $contentType = self::contentTypes['riskMaterializeDataset'][0])
    {
        list($response) = $this->riskMaterializeDatasetWithHttpInfo($name, $contentType);
        return $response;
    }

    /**
     * Operation riskMaterializeDatasetWithHttpInfo
     *
     * Materialise the declared version into immutable rows
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskMaterializeDataset'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\RiskDataset, HTTP status code, HTTP response headers (array of strings)
     */
    public function riskMaterializeDatasetWithHttpInfo($name, string $contentType = self::contentTypes['riskMaterializeDataset'][0])
    {
        $request = $this->riskMaterializeDatasetRequest($name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\RiskDataset',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\RiskDataset',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\RiskDataset',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation riskMaterializeDatasetAsync
     *
     * Materialise the declared version into immutable rows
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskMaterializeDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskMaterializeDatasetAsync($name, string $contentType = self::contentTypes['riskMaterializeDataset'][0])
    {
        return $this->riskMaterializeDatasetAsyncWithHttpInfo($name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation riskMaterializeDatasetAsyncWithHttpInfo
     *
     * Materialise the declared version into immutable rows
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskMaterializeDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function riskMaterializeDatasetAsyncWithHttpInfo($name, string $contentType = self::contentTypes['riskMaterializeDataset'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\RiskDataset';
        $request = $this->riskMaterializeDatasetRequest($name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'riskMaterializeDataset'
     *
     * @param  string $name Name is the dataset, from the path. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['riskMaterializeDataset'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function riskMaterializeDatasetRequest($name, string $contentType = self::contentTypes['riskMaterializeDataset'][0])
    {

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling riskMaterializeDataset'
            );
        }


        $resourcePath = '/v1/dataset/{name}/materialize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
