<?php
/**
 * GraphApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hanzo Cloud API
 *
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hanzo\Cloud\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Hanzo\Cloud\ApiException;
use Hanzo\Cloud\Configuration;
use Hanzo\Cloud\FormDataProcessor;
use Hanzo\Cloud\HeaderSelector;
use Hanzo\Cloud\ObjectSerializer;

/**
 * GraphApi Class Doc Comment
 *
 * @category Class
 * @package  Hanzo\Cloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GraphApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'graphAssert' => [
            'application/json',
        ],
        'graphNeighbors' => [
            'application/json',
        ],
        'graphRead' => [
            'application/json',
        ],
        'graphResolve' => [
            'application/json',
        ],
        'graphSearch' => [
            'application/json',
        ],
        'graphVocabulary' => [
            'application/json',
        ],
        'postGraphGraphql' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation graphAssert
     *
     * Assert what is true of an entity
     *
     * @param  \Hanzo\Cloud\Model\GraphAssertIn $graph_assert_in graph_assert_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphAssert'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphAssertOut
     */
    public function graphAssert($graph_assert_in, string $contentType = self::contentTypes['graphAssert'][0])
    {
        list($response) = $this->graphAssertWithHttpInfo($graph_assert_in, $contentType);
        return $response;
    }

    /**
     * Operation graphAssertWithHttpInfo
     *
     * Assert what is true of an entity
     *
     * @param  \Hanzo\Cloud\Model\GraphAssertIn $graph_assert_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphAssert'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphAssertOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphAssertWithHttpInfo($graph_assert_in, string $contentType = self::contentTypes['graphAssert'][0])
    {
        $request = $this->graphAssertRequest($graph_assert_in, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphAssertOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphAssertOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphAssertOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphAssertAsync
     *
     * Assert what is true of an entity
     *
     * @param  \Hanzo\Cloud\Model\GraphAssertIn $graph_assert_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphAssert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphAssertAsync($graph_assert_in, string $contentType = self::contentTypes['graphAssert'][0])
    {
        return $this->graphAssertAsyncWithHttpInfo($graph_assert_in, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphAssertAsyncWithHttpInfo
     *
     * Assert what is true of an entity
     *
     * @param  \Hanzo\Cloud\Model\GraphAssertIn $graph_assert_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphAssert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphAssertAsyncWithHttpInfo($graph_assert_in, string $contentType = self::contentTypes['graphAssert'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphAssertOut';
        $request = $this->graphAssertRequest($graph_assert_in, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphAssert'
     *
     * @param  \Hanzo\Cloud\Model\GraphAssertIn $graph_assert_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphAssert'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphAssertRequest($graph_assert_in, string $contentType = self::contentTypes['graphAssert'][0])
    {

        // verify the required parameter 'graph_assert_in' is set
        if ($graph_assert_in === null || (is_array($graph_assert_in) && count($graph_assert_in) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $graph_assert_in when calling graphAssert'
            );
        }


        $resourcePath = '/v1/graph';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($graph_assert_in)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($graph_assert_in));
            } else {
                $httpBody = $graph_assert_in;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation graphNeighbors
     *
     * Walk the edges from a seed set, bounded
     *
     * @param  \Hanzo\Cloud\Model\GraphNeighborsIn $graph_neighbors_in graph_neighbors_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphNeighbors'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphNeighborsOut
     */
    public function graphNeighbors($graph_neighbors_in, string $contentType = self::contentTypes['graphNeighbors'][0])
    {
        list($response) = $this->graphNeighborsWithHttpInfo($graph_neighbors_in, $contentType);
        return $response;
    }

    /**
     * Operation graphNeighborsWithHttpInfo
     *
     * Walk the edges from a seed set, bounded
     *
     * @param  \Hanzo\Cloud\Model\GraphNeighborsIn $graph_neighbors_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphNeighbors'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphNeighborsOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphNeighborsWithHttpInfo($graph_neighbors_in, string $contentType = self::contentTypes['graphNeighbors'][0])
    {
        $request = $this->graphNeighborsRequest($graph_neighbors_in, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphNeighborsOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphNeighborsOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphNeighborsOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphNeighborsAsync
     *
     * Walk the edges from a seed set, bounded
     *
     * @param  \Hanzo\Cloud\Model\GraphNeighborsIn $graph_neighbors_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphNeighborsAsync($graph_neighbors_in, string $contentType = self::contentTypes['graphNeighbors'][0])
    {
        return $this->graphNeighborsAsyncWithHttpInfo($graph_neighbors_in, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphNeighborsAsyncWithHttpInfo
     *
     * Walk the edges from a seed set, bounded
     *
     * @param  \Hanzo\Cloud\Model\GraphNeighborsIn $graph_neighbors_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphNeighborsAsyncWithHttpInfo($graph_neighbors_in, string $contentType = self::contentTypes['graphNeighbors'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphNeighborsOut';
        $request = $this->graphNeighborsRequest($graph_neighbors_in, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphNeighbors'
     *
     * @param  \Hanzo\Cloud\Model\GraphNeighborsIn $graph_neighbors_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphNeighbors'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphNeighborsRequest($graph_neighbors_in, string $contentType = self::contentTypes['graphNeighbors'][0])
    {

        // verify the required parameter 'graph_neighbors_in' is set
        if ($graph_neighbors_in === null || (is_array($graph_neighbors_in) && count($graph_neighbors_in) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $graph_neighbors_in when calling graphNeighbors'
            );
        }


        $resourcePath = '/v1/graph/neighbors';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($graph_neighbors_in)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($graph_neighbors_in));
            } else {
                $httpBody = $graph_neighbors_in;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation graphRead
     *
     * Read the assertions this organization has recorded
     *
     * @param  string|null $entity Entity narrows to what was asserted ABOUT one entity. Absent matches every entity. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $value Value narrows to assertions pointing AT one value, which is how the edges into an entity are read. (optional)
     * @param  string|null $as_of AsOf bounds the read to what was knowable at an instant, RFC 3339. Absent reads everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphRead'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphReadOut
     */
    public function graphRead($entity = null, $relation = null, $value = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphRead'][0])
    {
        list($response) = $this->graphReadWithHttpInfo($entity, $relation, $value, $as_of, $limit, $contentType);
        return $response;
    }

    /**
     * Operation graphReadWithHttpInfo
     *
     * Read the assertions this organization has recorded
     *
     * @param  string|null $entity Entity narrows to what was asserted ABOUT one entity. Absent matches every entity. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $value Value narrows to assertions pointing AT one value, which is how the edges into an entity are read. (optional)
     * @param  string|null $as_of AsOf bounds the read to what was knowable at an instant, RFC 3339. Absent reads everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphRead'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphReadOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphReadWithHttpInfo($entity = null, $relation = null, $value = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphRead'][0])
    {
        $request = $this->graphReadRequest($entity, $relation, $value, $as_of, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphReadOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphReadOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphReadOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphReadAsync
     *
     * Read the assertions this organization has recorded
     *
     * @param  string|null $entity Entity narrows to what was asserted ABOUT one entity. Absent matches every entity. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $value Value narrows to assertions pointing AT one value, which is how the edges into an entity are read. (optional)
     * @param  string|null $as_of AsOf bounds the read to what was knowable at an instant, RFC 3339. Absent reads everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphRead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphReadAsync($entity = null, $relation = null, $value = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphRead'][0])
    {
        return $this->graphReadAsyncWithHttpInfo($entity, $relation, $value, $as_of, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphReadAsyncWithHttpInfo
     *
     * Read the assertions this organization has recorded
     *
     * @param  string|null $entity Entity narrows to what was asserted ABOUT one entity. Absent matches every entity. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $value Value narrows to assertions pointing AT one value, which is how the edges into an entity are read. (optional)
     * @param  string|null $as_of AsOf bounds the read to what was knowable at an instant, RFC 3339. Absent reads everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphRead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphReadAsyncWithHttpInfo($entity = null, $relation = null, $value = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphRead'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphReadOut';
        $request = $this->graphReadRequest($entity, $relation, $value, $as_of, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphRead'
     *
     * @param  string|null $entity Entity narrows to what was asserted ABOUT one entity. Absent matches every entity. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $value Value narrows to assertions pointing AT one value, which is how the edges into an entity are read. (optional)
     * @param  string|null $as_of AsOf bounds the read to what was knowable at an instant, RFC 3339. Absent reads everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphRead'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphReadRequest($entity = null, $relation = null, $value = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphRead'][0])
    {







        $resourcePath = '/v1/graph';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $entity,
            'entity', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $relation,
            'relation', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $value,
            'value', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $as_of,
            'as_of', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation graphResolve
     *
     * What is in force about an entity as of an instant, and what disagreed
     *
     * @param  \Hanzo\Cloud\Model\GraphResolveIn $graph_resolve_in graph_resolve_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphResolve'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphResolveOut
     */
    public function graphResolve($graph_resolve_in, string $contentType = self::contentTypes['graphResolve'][0])
    {
        list($response) = $this->graphResolveWithHttpInfo($graph_resolve_in, $contentType);
        return $response;
    }

    /**
     * Operation graphResolveWithHttpInfo
     *
     * What is in force about an entity as of an instant, and what disagreed
     *
     * @param  \Hanzo\Cloud\Model\GraphResolveIn $graph_resolve_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphResolve'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphResolveOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphResolveWithHttpInfo($graph_resolve_in, string $contentType = self::contentTypes['graphResolve'][0])
    {
        $request = $this->graphResolveRequest($graph_resolve_in, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphResolveOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphResolveOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphResolveOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphResolveAsync
     *
     * What is in force about an entity as of an instant, and what disagreed
     *
     * @param  \Hanzo\Cloud\Model\GraphResolveIn $graph_resolve_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphResolve'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphResolveAsync($graph_resolve_in, string $contentType = self::contentTypes['graphResolve'][0])
    {
        return $this->graphResolveAsyncWithHttpInfo($graph_resolve_in, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphResolveAsyncWithHttpInfo
     *
     * What is in force about an entity as of an instant, and what disagreed
     *
     * @param  \Hanzo\Cloud\Model\GraphResolveIn $graph_resolve_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphResolve'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphResolveAsyncWithHttpInfo($graph_resolve_in, string $contentType = self::contentTypes['graphResolve'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphResolveOut';
        $request = $this->graphResolveRequest($graph_resolve_in, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphResolve'
     *
     * @param  \Hanzo\Cloud\Model\GraphResolveIn $graph_resolve_in (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphResolve'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphResolveRequest($graph_resolve_in, string $contentType = self::contentTypes['graphResolve'][0])
    {

        // verify the required parameter 'graph_resolve_in' is set
        if ($graph_resolve_in === null || (is_array($graph_resolve_in) && count($graph_resolve_in) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $graph_resolve_in when calling graphResolve'
            );
        }


        $resourcePath = '/v1/graph/resolve';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($graph_resolve_in)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($graph_resolve_in));
            } else {
                $httpBody = $graph_resolve_in;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation graphSearch
     *
     * Find assertions by their text rather than by an entity key
     *
     * @param  string|null $q Q is what to look for: words, matched as prefixes, all of them required. Punctuation is text here rather than syntax, so an entity key searches as itself. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $as_of AsOf bounds the search to what was knowable at an instant, RFC 3339. Absent searches everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphSearch'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphReadOut
     */
    public function graphSearch($q = null, $relation = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphSearch'][0])
    {
        list($response) = $this->graphSearchWithHttpInfo($q, $relation, $as_of, $limit, $contentType);
        return $response;
    }

    /**
     * Operation graphSearchWithHttpInfo
     *
     * Find assertions by their text rather than by an entity key
     *
     * @param  string|null $q Q is what to look for: words, matched as prefixes, all of them required. Punctuation is text here rather than syntax, so an entity key searches as itself. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $as_of AsOf bounds the search to what was knowable at an instant, RFC 3339. Absent searches everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphSearch'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphReadOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphSearchWithHttpInfo($q = null, $relation = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphSearch'][0])
    {
        $request = $this->graphSearchRequest($q, $relation, $as_of, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphReadOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphReadOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphReadOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphSearchAsync
     *
     * Find assertions by their text rather than by an entity key
     *
     * @param  string|null $q Q is what to look for: words, matched as prefixes, all of them required. Punctuation is text here rather than syntax, so an entity key searches as itself. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $as_of AsOf bounds the search to what was knowable at an instant, RFC 3339. Absent searches everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphSearchAsync($q = null, $relation = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphSearch'][0])
    {
        return $this->graphSearchAsyncWithHttpInfo($q, $relation, $as_of, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphSearchAsyncWithHttpInfo
     *
     * Find assertions by their text rather than by an entity key
     *
     * @param  string|null $q Q is what to look for: words, matched as prefixes, all of them required. Punctuation is text here rather than syntax, so an entity key searches as itself. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $as_of AsOf bounds the search to what was knowable at an instant, RFC 3339. Absent searches everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphSearchAsyncWithHttpInfo($q = null, $relation = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphSearch'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphReadOut';
        $request = $this->graphSearchRequest($q, $relation, $as_of, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphSearch'
     *
     * @param  string|null $q Q is what to look for: words, matched as prefixes, all of them required. Punctuation is text here rather than syntax, so an entity key searches as itself. (optional)
     * @param  string|null $relation Relation narrows to one relation. Absent matches every relation. (optional)
     * @param  string|null $as_of AsOf bounds the search to what was knowable at an instant, RFC 3339. Absent searches everything this plane holds. (optional)
     * @param  int|null $limit Limit caps how many assertions come back. Absent, zero, or anything above the walk ceiling is the ceiling. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphSearch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphSearchRequest($q = null, $relation = null, $as_of = null, $limit = null, string $contentType = self::contentTypes['graphSearch'][0])
    {






        $resourcePath = '/v1/graph/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $relation,
            'relation', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $as_of,
            'as_of', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation graphVocabulary
     *
     * The relations in use, and the rule that resolves a conflict
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphVocabulary'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphVocabularyOut
     */
    public function graphVocabulary(string $contentType = self::contentTypes['graphVocabulary'][0])
    {
        list($response) = $this->graphVocabularyWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation graphVocabularyWithHttpInfo
     *
     * The relations in use, and the rule that resolves a conflict
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphVocabulary'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphVocabularyOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function graphVocabularyWithHttpInfo(string $contentType = self::contentTypes['graphVocabulary'][0])
    {
        $request = $this->graphVocabularyRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Hanzo\Cloud\Model\GraphVocabularyOut',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphVocabularyOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Hanzo\Cloud\Model\GraphVocabularyOut',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation graphVocabularyAsync
     *
     * The relations in use, and the rule that resolves a conflict
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphVocabulary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphVocabularyAsync(string $contentType = self::contentTypes['graphVocabulary'][0])
    {
        return $this->graphVocabularyAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation graphVocabularyAsyncWithHttpInfo
     *
     * The relations in use, and the rule that resolves a conflict
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphVocabulary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function graphVocabularyAsyncWithHttpInfo(string $contentType = self::contentTypes['graphVocabulary'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphVocabularyOut';
        $request = $this->graphVocabularyRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'graphVocabulary'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['graphVocabulary'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function graphVocabularyRequest(string $contentType = self::contentTypes['graphVocabulary'][0])
    {


        $resourcePath = '/v1/graph/vocabulary';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postGraphGraphql
     *
     * Ask the graph in one request, traversing.
     *
     * @param  \Hanzo\Cloud\Model\GraphQLIn|null $graph_qlin graph_qlin (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postGraphGraphql'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Hanzo\Cloud\Model\GraphQLOut
     */
    public function postGraphGraphql($graph_qlin = null, string $contentType = self::contentTypes['postGraphGraphql'][0])
    {
        list($response) = $this->postGraphGraphqlWithHttpInfo($graph_qlin, $contentType);
        return $response;
    }

    /**
     * Operation postGraphGraphqlWithHttpInfo
     *
     * Ask the graph in one request, traversing.
     *
     * @param  \Hanzo\Cloud\Model\GraphQLIn|null $graph_qlin (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postGraphGraphql'] to see the possible values for this operation
     *
     * @throws \Hanzo\Cloud\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Hanzo\Cloud\Model\GraphQLOut, HTTP status code, HTTP response headers (array of strings)
     */
    public function postGraphGraphqlWithHttpInfo($graph_qlin = null, string $contentType = self::contentTypes['postGraphGraphql'][0])
    {
        $request = $this->postGraphGraphqlRequest($graph_qlin, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                
            }

            if ($this->responseWithinRangeCode('2XX', $statusCode)) {
                return $this->handleResponseWithDataType(
                    '\Hanzo\Cloud\Model\GraphQLOut',
                    $request,
                    $response,
                );
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Hanzo\Cloud\Model\GraphQLOut',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                
            }
        
            if ($this->responseWithinRangeCode('2XX', $e->getCode())) {
                $data = ObjectSerializer::deserialize(
                    $e->getResponseBody(),
                    '\Hanzo\Cloud\Model\GraphQLOut',
                    $e->getResponseHeaders()
                );
                $e->setResponseObject($data);
                throw $e;
            }

            throw $e;
        }
    }

    /**
     * Operation postGraphGraphqlAsync
     *
     * Ask the graph in one request, traversing.
     *
     * @param  \Hanzo\Cloud\Model\GraphQLIn|null $graph_qlin (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postGraphGraphql'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGraphGraphqlAsync($graph_qlin = null, string $contentType = self::contentTypes['postGraphGraphql'][0])
    {
        return $this->postGraphGraphqlAsyncWithHttpInfo($graph_qlin, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postGraphGraphqlAsyncWithHttpInfo
     *
     * Ask the graph in one request, traversing.
     *
     * @param  \Hanzo\Cloud\Model\GraphQLIn|null $graph_qlin (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postGraphGraphql'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postGraphGraphqlAsyncWithHttpInfo($graph_qlin = null, string $contentType = self::contentTypes['postGraphGraphql'][0])
    {
        $returnType = '\Hanzo\Cloud\Model\GraphQLOut';
        $request = $this->postGraphGraphqlRequest($graph_qlin, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postGraphGraphql'
     *
     * @param  \Hanzo\Cloud\Model\GraphQLIn|null $graph_qlin (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postGraphGraphql'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postGraphGraphqlRequest($graph_qlin = null, string $contentType = self::contentTypes['postGraphGraphql'][0])
    {



        $resourcePath = '/v1/graph/graphql';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($graph_qlin)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($graph_qlin));
            } else {
                $httpBody = $graph_qlin;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
